server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://139.196.162.227:3306/db_basedata_center?characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: boss-bes-basedata
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 172.20.0.219:8761
  client:
    serviceUrl:
      defaultZone: http://172.20.0.219:8761/eureka/
